### ISSUE TITLE
missing dependencies

### ISSUE THREAD

**Issue by taylorjensen10** [Lyall/SyberiaTWBFix#4] opened 2022-05-05 03:15 UTC
the fix was working for about a week and around the time the game got updated it would no longer work I tried starting with a fresh install but nothing changed. I am not sure if its a melon loader problem or a game problem. I am not good with tech so I am not sure if this is the right thing to paste in here.

22:06:39.349] ------------------------------
[22:06:39.349] MelonLoader v0.5.4 Open-Beta
[22:06:39.350] OS: Windows 10
[22:06:39.350] Hash Code: 99102531024810154100579910097100505048995753975597975597101485351514856
[22:06:39.350] ------------------------------
[22:06:39.350] Game Type: MonoBleedingEdge
[22:06:39.351] Game Arch: x64
[22:06:39.351] ------------------------------
[22:06:39.351] Core::BasePath = C:\Program Files (x86)\Steam\steamapps\common\Syberia - The World Before
[22:06:39.352] Game::BasePath = C:\Program Files (x86)\Steam\steamapps\common\Syberia - The World Before
[22:06:39.352] Game::DataPath = C:\Program Files (x86)\Steam\steamapps\common\Syberia - The World Before\SyberiaTWB_Data
[22:06:39.352] Game::ApplicationPath = C:\Program Files (x86)\Steam\steamapps\common\Syberia - The World Before\SyberiaTWB.exe

[22:06:40.477] ------------------------------
[22:06:40.477] Game Name: SyberiaTWB
[22:06:40.478] Game Developer: Microids
[22:06:40.479] Unity Version: 2020.3.25f1
[22:06:40.479] Game Version: 1.0
[22:06:40.479] ------------------------------
[22:06:40.734] Preferences Loaded!
[22:06:40.748] Loading Plugins...

[22:06:40.751] ------------------------------
[22:06:40.752] No Plugins Loaded!
[22:06:40.752] ------------------------------

[22:06:42.132] Loading Mods...
[22:06:42.151] [WARNING] Some Melons are missing dependencies, which you may have to install.
If these are optional dependencies, mark them as optional using the MelonOptionalDependencies attribute.
This warning will turn into an error and Melons with missing dependencies will not be loaded in the next version of MelonLoader.
- 'Syberia: The World Before Fix' is missing the following dependencies:
    - 'UnhollowerBaseLib' v0.4.17.0
    - 'Il2Cppmscorlib' v4.0.0.0

[22:06:42.153] ------------------------------
[22:06:42.153] 1 Mod Loaded
[22:06:42.154] ------------------------------
[22:06:42.154] Syberia: The World Before Fix v1.0.2
[22:06:42.154] by Lyall
[22:06:42.156] SHA256 Hash: 3e4d7ab81a01f769212d765718272671c240785d48e8897a361c0c1bfc88351f
[22:06:42.156] ------------------------------
[22:06:42.158] [WARNING] Some Melons are missing dependencies, which you may have to install.
If these are optional dependencies, mark them as optional using the MelonOptionalDependencies attribute.
This warning will turn into an error and Melons with missing dependencies will not be loaded in the next version of MelonLoader.
- 'Syberia: The World Before Fix' is missing the following dependencies:
    - 'UnhollowerBaseLib' v0.4.17.0
    - 'Il2Cppmscorlib' v4.0.0.0
[22:06:42.209] [Syberia:_The_World_Before_Fix] Application started.
[22:06:42.221] MelonPreferences Loaded from Mods/SyberiaTWBFix.cfg
[22:06:42.225] [WARNING] Some Melons are missing dependencies, which you may have to install.
If these are optional dependencies, mark them as optional using the MelonOptionalDependencies attribute.
This warning will turn into an error and Melons with missing dependencies will not be loaded in the next version of MelonLoader.
- 'Syberia: The World Before Fix' is missing the following dependencies:
    - 'UnhollowerBaseLib' v0.4.17.0
    - 'Il2Cppmscorlib' v4.0.0.0
[22:06:48.412] [Syberia:_The_World_Before_Fix] [ERROR] System.IO.FileNotFoundException: Could not load file or assembly 'UnhollowerBaseLib, Version=0.4.17.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
File name: 'UnhollowerBaseLib, Version=0.4.17.0, Culture=neutral, PublicKeyToken=null'
  at MelonLoader.MelonHandler+<>c__DisplayClass46_0.<OnSceneWasLoaded>b__0 (MelonLoader.MelonMod x) [0x0000c] in <0f6d2009dc5d4313a30db0346f3f685b>:0
  at MelonLoader.MelonHandler.InvokeMelonMethod[T] (System.Collections.Generic.List`1[T]& melons, MelonLoader.MelonHandler+InvokeMelonMethodDelegate`1[T] method, System.Boolean remove_failed) [0x00032] in <0f6d2009dc5d4313a30db0346f3f685b>:0
[22:06:48.615] [Syberia:_The_World_Before_Fix] Skipped intro.
[22:06:48.648] [WARNING] Some Melons are missing dependencies, which you may have to install.
If these are optional dependencies, mark them as optional using the MelonOptionalDependencies attribute.
This warning will turn into an error and Melons with missing dependencies will not be loaded in the next version of MelonLoader.
- 'Syberia: The World Before Fix' is missing the following dependencies:
    - 'UnhollowerBaseLib' v0.4.17.0
    - 'Il2Cppmscorlib' v4.0.0.0
geforcenowdetect():GfnInitializeSdkFromPath(GfnRuntimeSdk.dll): -28.
geforcenowdetect():GfnInitializeSdkFromPath(Assets\Plugins\geforcenowdetect\GfnRuntimeSdk.dll): -28.
geforcenowdetect():GfnInitializeSdkFromPath(SyberiaTWB_Data\Plugins\x86_64\GfnRuntimeSdk.dll): 1.
geforcenowdetect():GfnIsRunningInCloud():false.
[22:06:50.476] [Syberia:_The_World_Before_Fix] [ERROR] System.IO.FileNotFoundException: Could not load file or assembly 'UnhollowerBaseLib, Version=0.4.17.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
File name: 'UnhollowerBaseLib, Version=0.4.17.0, Culture=neutral, PublicKeyToken=null'
  at MelonLoader.MelonHandler+<>c__DisplayClass46_0.<OnSceneWasLoaded>b__0 (MelonLoader.MelonMod x) [0x0000c] in <0f6d2009dc5d4313a30db0346f3f685b>:0
  at MelonLoader.MelonHandler.InvokeMelonMethod[T] (System.Collections.Generic.List`1[T]& melons, MelonLoader.MelonHandler+InvokeMelonMethodDelegate`1[T] method, System.Boolean remove_failed) [0x00032] in <0f6d2009dc5d4313a30db0346f3f685b>:0
Setting breakpad minidump AppID = 1410640
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561198400312723 [API loaded no]

**Comment by Lyall** [comment] 2022-05-05 08:49
Hey, so the problem is that in the last game update they switched from IL2CPP to Mono. It's kind of an odd decision, most games I've seen have gone from Mono to IL2CPP instead. Which basically means that I have to retarget the mod for the latest build of the game. This may take me a little while as I have to rewrite parts of the mod.

**Comment by Lyall** [comment] 2022-05-05 09:52
Looks like it actually wasn't that difficult. I've put up a new release that should work on the latest version of the game. 

https://github.com/Lyall/SyberiaTWBFix/releases/tag/v1.0.3

Let me know if all is working for you and I'll close the issue.

**Comment by taylorjensen10** [comment] 2022-05-06 01:29
it seems to be working perfectly thank you very much.

**Comment by Lyall** [comment] 2022-05-06 07:08
That's great to hear. I'll close the issue now.

**Closed as completed by Lyall** 2022-05-06 07:08 UTC
